import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lazy-Panda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <div className={styles.panda}>
        <h1>&lt;Lazy-panda/&gt;</h1>
      </div>
      <div className={styles.pandaImg}>
        <Image src="/download_panda.png" alt="Picture of the author" width={200} height={200}
        />
      </div>
      <div className={styles.info}>
        <p className={styles.para}>A blog for lazy panda coders...AI- driven personalised, curation service for quality programming content. A platform for developers, that provides you with a personalised curation service on programming topics. Use it to write and read quality articles on programming. Not for content-marketing disguised as programming tutorials.
        </p>
      </div>
      <main className={styles.main}>

        <div className={styles.blogs}>
          <div className={styles.popBolg}>
            <h2 >Latest Blogs</h2>
          </div>
          <div className={styles.conta}>
            <div className={styles.blogItem}>
              <h3>How to learn javascript in 2023 ?</h3>
              <p className={styles.paraa}>Java Script is the lanuage for web-app.</p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn javascript in 2023 ?</h3>
              <p className={styles.paraa}>Java Script is the lanuage for web-app.</p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn javascript in 2023 ?</h3>
              <p className={styles.paraa}>Java Script is the lanuage for web-app.</p>
              <button className={styles.btn}>Read More</button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
